/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package core.views;

import core.controllers.login.LoginController;
import core.controllers.user.UserController;
import core.controllers.utils.Response;
import core.controllers.utils.Status;
import java.awt.Color;
import java.time.LocalDate;
import core.models.storage.IStorage;
import java.util.HashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author jjlora
 * @author edangulo
 */
public class LogRegView extends javax.swing.JFrame {

    private int x, y;
    private final LoginController loginController;
    private final IStorage storage;
    private final UserController userController;

    public LogRegView(IStorage storage) {
        initComponents();
        this.setBackground(new Color(0, 0, 0, 0));
        this.setLocationRelativeTo(null);
        this.storage = storage;
        this.loginController = new LoginController(this.storage);
        this.userController = new UserController(this.storage);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFullBg = new core.views.utils.PanelRound();
        pnlExit = new core.views.utils.PanelRound();
        btnExit = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlLogin = new core.views.utils.PanelRound();
        lblLogin = new javax.swing.JLabel();
        txtUsernameLog = new javax.swing.JTextField();
        lblUsernameLog = new javax.swing.JLabel();
        txtPasswordLog = new javax.swing.JTextField();
        lblPasswordLog = new javax.swing.JLabel();
        btnEnterLog = new javax.swing.JButton();
        pnlRegister = new javax.swing.JPanel();
        lblFirstNameReg = new javax.swing.JLabel();
        txtFirstNameReg = new javax.swing.JTextField();
        lblLastNameReg = new javax.swing.JLabel();
        txtLastNameReg = new javax.swing.JTextField();
        lblIdReg = new javax.swing.JLabel();
        txtIdReg = new javax.swing.JTextField();
        lblGenderReg = new javax.swing.JLabel();
        lblPhoneReg = new javax.swing.JLabel();
        txtPhoneReg = new javax.swing.JTextField();
        lblEmailReg = new javax.swing.JLabel();
        txtEmailReg = new javax.swing.JTextField();
        lblUserReg = new javax.swing.JLabel();
        txtUserReg = new javax.swing.JTextField();
        txtPasswordReg = new javax.swing.JTextField();
        lblPasswordReg = new javax.swing.JLabel();
        lblPassConfReg = new javax.swing.JLabel();
        txtPassConfReg = new javax.swing.JTextField();
        cmbGenderReg = new javax.swing.JComboBox<>();
        btnSaveReg = new javax.swing.JButton();
        lblAddressReg = new javax.swing.JLabel();
        txtAddressReg = new javax.swing.JTextField();
        lblBDateReg = new javax.swing.JLabel();
        txtBDateReg = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnlFullBg.setRadius(50);

        pnlExit.setRadius(50);
        pnlExit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlExitMouseDragged(evt);
            }
        });
        pnlExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlExitMousePressed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnExit.setText("X");
        btnExit.setBorderPainted(false);
        btnExit.setContentAreaFilled(false);
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnExit.setFocusable(false);
        btnExit.setRequestFocusEnabled(false);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlExitLayout = new javax.swing.GroupLayout(pnlExit);
        pnlExit.setLayout(pnlExitLayout);
        pnlExitLayout.setHorizontalGroup(
            pnlExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlExitLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExit)
                .addGap(19, 19, 19))
        );
        pnlExitLayout.setVerticalGroup(
            pnlExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnExit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        lblLogin.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        lblLogin.setText("LOGIN");

        txtUsernameLog.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtUsernameLog.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblUsernameLog.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblUsernameLog.setText("USERNAME");

        txtPasswordLog.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtPasswordLog.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblPasswordLog.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPasswordLog.setText("PASSWORD");

        btnEnterLog.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnEnterLog.setText("ENTER");
        btnEnterLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterLogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLoginLayout = new javax.swing.GroupLayout(pnlLogin);
        pnlLogin.setLayout(pnlLoginLayout);
        pnlLoginLayout.setHorizontalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginLayout.createSequentialGroup()
                .addContainerGap(475, Short.MAX_VALUE)
                .addComponent(lblLogin)
                .addGap(481, 481, 481))
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addGap(431, 431, 431)
                        .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginLayout.createSequentialGroup()
                                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPasswordLog, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblUsernameLog, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtPasswordLog, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtUsernameLog, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addGap(471, 471, 471)
                        .addComponent(btnEnterLog)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlLoginLayout.setVerticalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(lblLogin)
                .addGap(74, 74, 74)
                .addComponent(lblUsernameLog)
                .addGap(18, 18, 18)
                .addComponent(txtUsernameLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPasswordLog)
                .addGap(18, 18, 18)
                .addComponent(txtPasswordLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnEnterLog)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Login", pnlLogin);

        lblFirstNameReg.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblFirstNameReg.setText("Firstname");

        txtFirstNameReg.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblLastNameReg.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblLastNameReg.setText("Lastname");

        txtLastNameReg.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblIdReg.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblIdReg.setText("ID");

        txtIdReg.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblGenderReg.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblGenderReg.setText("Gender");

        lblPhoneReg.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPhoneReg.setText("Phone");

        txtPhoneReg.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblEmailReg.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblEmailReg.setText("Email");

        txtEmailReg.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblUserReg.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblUserReg.setText("User");

        txtUserReg.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        txtPasswordReg.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblPasswordReg.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPasswordReg.setText("Password");

        lblPassConfReg.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPassConfReg.setText("Password confirmation");

        txtPassConfReg.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtPassConfReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassConfRegActionPerformed(evt);
            }
        });

        cmbGenderReg.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cmbGenderReg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "Female", "Male" }));

        btnSaveReg.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnSaveReg.setText("Save");
        btnSaveReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveRegActionPerformed(evt);
            }
        });

        lblAddressReg.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblAddressReg.setText("Address");

        txtAddressReg.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblBDateReg.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblBDateReg.setText("Birthdate");

        txtBDateReg.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout pnlRegisterLayout = new javax.swing.GroupLayout(pnlRegister);
        pnlRegister.setLayout(pnlRegisterLayout);
        pnlRegisterLayout.setHorizontalGroup(
            pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegisterLayout.createSequentialGroup()
                .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRegisterLayout.createSequentialGroup()
                        .addGap(450, 450, 450)
                        .addComponent(lblPasswordReg))
                    .addGroup(pnlRegisterLayout.createSequentialGroup()
                        .addGap(434, 434, 434)
                        .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUserReg, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPasswordReg, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlRegisterLayout.createSequentialGroup()
                        .addGap(473, 473, 473)
                        .addComponent(lblUserReg))
                    .addGroup(pnlRegisterLayout.createSequentialGroup()
                        .addGap(432, 432, 432)
                        .addComponent(txtPassConfReg, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlRegisterLayout.createSequentialGroup()
                        .addGap(456, 456, 456)
                        .addComponent(btnSaveReg))
                    .addGroup(pnlRegisterLayout.createSequentialGroup()
                        .addGap(396, 396, 396)
                        .addComponent(lblPassConfReg))
                    .addGroup(pnlRegisterLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(pnlRegisterLayout.createSequentialGroup()
                                .addComponent(lblBDateReg)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtBDateReg, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlRegisterLayout.createSequentialGroup()
                                .addComponent(lblFirstNameReg)
                                .addGap(34, 34, 34)
                                .addComponent(txtFirstNameReg, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLastNameReg)
                            .addComponent(lblAddressReg))
                        .addGap(18, 18, 18)
                        .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlRegisterLayout.createSequentialGroup()
                                .addComponent(txtLastNameReg, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblIdReg)
                                .addGap(30, 30, 30)
                                .addComponent(txtIdReg, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblGenderReg)
                                .addGap(26, 26, 26)
                                .addComponent(cmbGenderReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlRegisterLayout.createSequentialGroup()
                                .addComponent(txtAddressReg, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblPhoneReg)
                                .addGap(18, 18, 18)
                                .addComponent(txtPhoneReg, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblEmailReg)
                                .addGap(18, 18, 18)
                                .addComponent(txtEmailReg, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        pnlRegisterLayout.setVerticalGroup(
            pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegisterLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstNameReg)
                    .addComponent(txtFirstNameReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLastNameReg)
                    .addComponent(txtLastNameReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdReg)
                    .addComponent(txtIdReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGenderReg)
                    .addComponent(cmbGenderReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblBDateReg)
                        .addComponent(txtBDateReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblAddressReg)
                        .addComponent(txtAddressReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPhoneReg)
                        .addComponent(txtPhoneReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblEmailReg)
                        .addComponent(txtEmailReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(lblUserReg)
                .addGap(18, 18, 18)
                .addComponent(txtUserReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPasswordReg)
                .addGap(18, 18, 18)
                .addComponent(txtPasswordReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPassConfReg)
                .addGap(18, 18, 18)
                .addComponent(txtPassConfReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnSaveReg)
                .addGap(42, 42, 42))
        );

        jTabbedPane1.addTab("Patient register", pnlRegister);

        javax.swing.GroupLayout pnlFullBgLayout = new javax.swing.GroupLayout(pnlFullBg);
        pnlFullBg.setLayout(pnlFullBgLayout);
        pnlFullBgLayout.setHorizontalGroup(
            pnlFullBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlFullBgLayout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1028, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlFullBgLayout.setVerticalGroup(
            pnlFullBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFullBgLayout.createSequentialGroup()
                .addComponent(pnlExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFullBg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFullBg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExitMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_pnlExitMousePressed

    private void pnlExitMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExitMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_pnlExitMouseDragged

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnEnterLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterLogActionPerformed
        String username = txtUsernameLog.getText();
        String password = txtPasswordLog.getText();

        Response response = loginController.loginUser(username, password);

        if (response.getStatus() == Status.OK) {
            HashMap<String, Object> userData = response.getData();
            String role = (String) userData.get("role");
            long id = (long) userData.get("id");
            this.dispose();

            if (role.equals("ADMIN")) {
                new AdminView(storage).setVisible(true);
            } else if (role.equals("DOCTOR")) {
                new DoctorView(storage, id).setVisible(true);
            } else {
                new PatientView(storage, id).setVisible(true);
            }
        } else {
            JOptionPane.showMessageDialog(this, response.getMessage(), "Error de autenticación", JOptionPane.ERROR_MESSAGE);
        }
        txtUsernameLog.setText("");
        txtPasswordLog.setText("");

    }//GEN-LAST:event_btnEnterLogActionPerformed

    private void btnSaveRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveRegActionPerformed
        String firstname = txtFirstNameReg.getText();
        String lastname = txtLastNameReg.getText();
        long id = Long.parseLong(txtIdReg.getText());
        Boolean gender = null;
        if (cmbGenderReg.getSelectedIndex() == 1) {
            gender = true;
        } else if (cmbGenderReg.getSelectedIndex() == 2) {
            gender = false;
        }

        String birth = txtBDateReg.getText();
        String address = txtAddressReg.getText();
        long phone = Long.parseLong(txtPhoneReg.getText());
        String email = txtEmailReg.getText();
        String user = txtUserReg.getText();
        String password = txtPasswordReg.getText();
        String comPassword = txtPassConfReg.getText();
        if (gender == null) {
            JOptionPane.showMessageDialog(this, "Seleccione el género");
            return;
        }
        UserController userController = new UserController(storage); // Necesitas pasarle el storage adecuado
        Response response = userController.registerPatient(
                firstname, lastname, id, gender, birth, address, phone, email, user, password, comPassword
        );
        if (response.getStatus() == Status.OK) {
            JOptionPane.showMessageDialog(this, "Registrado");
        } else {
            JOptionPane.showMessageDialog(this, response.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSaveRegActionPerformed

    private void txtPassConfRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassConfRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassConfRegActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnterLog;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSaveReg;
    private javax.swing.JComboBox<String> cmbGenderReg;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblAddressReg;
    private javax.swing.JLabel lblBDateReg;
    private javax.swing.JLabel lblEmailReg;
    private javax.swing.JLabel lblFirstNameReg;
    private javax.swing.JLabel lblGenderReg;
    private javax.swing.JLabel lblIdReg;
    private javax.swing.JLabel lblLastNameReg;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblPassConfReg;
    private javax.swing.JLabel lblPasswordLog;
    private javax.swing.JLabel lblPasswordReg;
    private javax.swing.JLabel lblPhoneReg;
    private javax.swing.JLabel lblUserReg;
    private javax.swing.JLabel lblUsernameLog;
    private core.views.utils.PanelRound pnlExit;
    private core.views.utils.PanelRound pnlFullBg;
    private core.views.utils.PanelRound pnlLogin;
    private javax.swing.JPanel pnlRegister;
    private javax.swing.JTextField txtAddressReg;
    private javax.swing.JTextField txtBDateReg;
    private javax.swing.JTextField txtEmailReg;
    private javax.swing.JTextField txtFirstNameReg;
    private javax.swing.JTextField txtIdReg;
    private javax.swing.JTextField txtLastNameReg;
    private javax.swing.JTextField txtPassConfReg;
    private javax.swing.JTextField txtPasswordLog;
    private javax.swing.JTextField txtPasswordReg;
    private javax.swing.JTextField txtPhoneReg;
    private javax.swing.JTextField txtUserReg;
    private javax.swing.JTextField txtUsernameLog;
    // End of variables declaration//GEN-END:variables
}
